apiVersion: v1
kind: Service
metadata:
  name: altered-datum-service
spec:
  selector:
    app: altered-datum
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
      nodePort: 32005
  type: NodePort